mity/acutest

- include/cutest.h
One is a missing return, the other is size_t for an int parameter in printf.
> Fix some valid GCC warnings

- include/cutest.h
Thanks for your handy test header. It is both lightweight and useful!
This pull request contains two commits:
- One commit replaces "\e" by its octal equivalent "\033". "\e" is a GNU extension and does not belong to the ISO C standard. [Ref](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Non-standard_escape_sequences)
- The other commit defines (if it is not defined) `_POSIX_C_SOURCE` as required by `man fileno` and moves the inclusion of some standard headers after the definition of `_POSIX_C_SOURCE` as required by `man feature_test_macros`. `cutest.h` has been assuming that if unix or APPLE is defined, then POSIX headers are available. This is false if for instance the `-ansi` flag is passed to the gcc compiler or if the `--std=c99` flag is used. By defining `_POSIX_C_SOURCE` we …
> POSIX fixes for standard C compatibility

- include/cutest.h
On b4c15484fe992 (see #5) I proposed defining `_POSIX_C_SOURCE` inside `cutest.h` in order to enable the macros to use POSIX under unix-like systems, as POSIX was used by cutest on those systems.
Here I propose to follow whatever the user wants. This means:
- If the user explicitly defines a strict standard C compliance (e.g. compiling using `--std=c99`) then we do not use any POSIX feature. This is detected through the definition of the __STRICT_ANSI__ macro.
- If the user does not enforce any C standard, we assume POSIX is available if the system is unix-like, as before.
I believe this approach is better than the previous one because if any cutest user does not want to rely on POSIX features we won't enable them and we won't use them. However by default we use them if they are …
> Do not add feature test macros

- include/acutest.h
> Fix `isatty` build error with Embarcadero C++ Builder.

- include/acutest.h
> Implement TAP (https://testanything.org/)

- examples/cpp-example.cc
- include/acutest.h
Useful for integration into CI systems. Doesn't currently capture the actual error messages.
In the process I've also removed the 'tests__' copy of test_list__ and just use the flags instead. I don't think this will have a significant impact, but I'm open to comments. It makes it easier to know which index you're at for setting the SUCCESS/FAILURE flags.
The more complex next step would be to capture the output of each command and save it in a buffer to jam into the report. At this stage I've just left that, so people will need to look at the logs to see the details of the error.
> Xunit support

- include/acutest.h
Replaced test_flags__ with a per-test test_detail__ structure.
Use this for both flags & holding timing information.
This allows us to add the timing information to the xml report.
> Added per-test timing support

- include/acutest.h
This is used to fill in the xml test report.
Tested on Unix, untested on Win32
> Extract test name from executable

- include/acutest.h
Just a few typos picked up when checking our code with [codespell](https://github.com/codespell-project/codespell).
(and one trailing space char in the code)
> fix spelling

- include/acutest.h
I may be miss using this, but shouldn't the abort be conditional?
> TEST_ASSERT: Only abort if the check fails

- include/acutest.h
fixes #28 Timing calculations are wrong
fixes #29 TEST_CASE should evaluate as a statement (no trailing semicolon)
I've added my copyright as a "Portions" bit.  If you prefer to instead just have me add a Copyright line below yours (how I do it for my repos), please let me know (or just make the change yourself).
Meaning, I'm also happy with:
```
* Copyright (c) 2013-2019 Martin Mitas
* Copyright 2019 Garrett D'Amore 
*
* ... license text follows
```
Oh, and thanks for your work on this project -- I'm now using it in NNG (as you know), and have begin replacing my own framework (c-convey -- see github.com/gdamore/c-convey) with it as this is simply easier to use and debug.
As an aside, the "(c)" in your copyright statement is actually useless (following a bad practice started by companies …
> Fixes for timing and clang-tidy use.

- include/acutest.h
Disabling exec when running in a debugger is awesome! This PR does the same when running under valgrind.
Detecting valgrind is normally done by including `valgrind.h` which provides a `RUNNING_ON_VALGRIND` macro. This simple PR doesn't `#include` anything, it just uses `RUNNING_ON_VALGRIND` if present, the user just needs to include `valgrind.h` before including `acutest.h`.
> Disable exec when running under valgrind

- include/acutest.h
Fixes some minor warnings found when moving acutest test suites to our main build system.  
The only really contentious issue there is the use of `__attribute__` as it's non standard.  If this is a problem I'm happy to change to using a preprocessor macro that the user can explicitly enable if they need a build without warnings and are using a compiler that supports `__attribute__` (Clang/GCC).
> Fixes warnings seen with clang 9.0.0

- include/acutest.h
When using cppcheck with acutest there are some warnings that it flags.
These are all minor, but it would be nice to not have them show up.
The following are the ones addressed here:
[include/acutest.h:560]: (warning) %u in format string (no. 2) requires 'unsigned int' but the argument type is 'signed int'.
[include/acutest.h:831]: (style) The scope of the variable 'starts_on_word_boundary' can be reduced.
[include/acutest.h:832]: (style) The scope of the variable 'ends_on_word_boundary' can be reduced.
[include/acutest.h:895]: (style) The scope of the variable 'args' can be reduced.
> Clean up some warnings from cppcheck

- include/acutest.h
The `TEST_CASE()` macro is limited to 64 chars.
Define a constant, `TEST_CASE_MAXSIZE`, defaulting to 64,
but allow the user to override it.
---
A lot of our test cases are paths, so often 64 chars isn't enough.
> Allow bigger TEST_CASE() names

- include/acutest.h
- `test_global_init()` is called before every test
- `test_global_fini()` is called after every test
The user can define code to be called by defining `TEST_GLOBAL_INIT`
and/or `TEST_GLOBAL_FINI`.
```c
#ifdef TEST_GLOBAL_INIT { printf("before %s\n", test_case); }
#ifdef TEST_GLOBAL_FINI { printf("after %s\n", test_case); }
#include "acutest.h"
```
Closes: #46 
---
I've implemented the functions as you suggested and they work nicely.
A few notes:
- The `test_global_init()` is inside the `try` block.
I moved the `test_begin_test_line_()` call after so that the `test... [OK]` line won't get split up.
- The `test_global_fini()` is also inside the `try` block.
This means it won't get called after a crash, probably not a problem :-)
- I dropped the lone `;` since that will lead to build …
> Add functions that are called before/after every test

- include/acutest.h
g++ 10 on ubuntu was not producing the expected #define
> fix broken OS detection

- include/acutest.h
As per title, fixes:
```
src/freeradius-devel/util/acutest.h:409:1: warning: function 'test_exit_' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
{
^
1 warning generated.
```
> Fix -Wmissing-noreturn with clang11

- include/acutest.h
Make a clearer distinction between the public API and the implementation
so that public staf begins "TEST_" and all internal stuff begins with
the prefix "ACUTEST_" or "acutest_".
> Code cleanup.

- README.md
- include/acutest.h
Since debugger detection is already present on both Linux and Windows, I took the liberty to add support for macOS as well. The implementation is based upon [Detecting the Debugger](https://developer.apple.com/library/archive/qa/qa1361/_index.html) provided by [Apple](http://apple.com).
Closes #36
> Macos debugging

- include/acutest.h
In non main files there is no need to compile + include so much things.
In my system some of the includes made problems
> remove non needed things from non main files
